# Project information

site_name: Identity Round Robin
site_short_name: Identity Round Robin
site_description: 'A hands-on workshop to learn about a variety of AWS identity topics.'
# site_author: 'aws-security-workshops@amazon.com'
# site_url: 'https://identity-round-robin.awssecworkshops.com/'

# Repository
#repo_name: 'aws-samples/aws-identity-round-robin-workshop'
#repo_url: 'https://github.com/aws-samples/aws-identity-round-robin-workshop'
repo_name: ' skiritan/aws-identity-round-robin-workshop'
repo_url: 'https://github.com/skiritan/aws-identity-round-robin-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details


# Navigation
nav:
  - '概要': 'index.md'
  - 'サーバレスアイデンティティ':
    - 'シナリオ': 'serverless/index.md'
    - 'タスク１': 'serverless/task1.md'
    - 'タスク２': 'serverless/task2.md'
  - 'アクセス委任':
    - 'シナリオ': 'delegation/index.md'
    - '構築フェーズ': 'delegation/build.md'
    - '検証フェーズ': 'delegation/verify.md'
  - 'パーミッションバウンダリー':
    - 'シナリオ': 'permission-boundaries/index.md'
    - '構築フェーズ': 'permission-boundaries/build.md'
    - '検証フェーズ': 'permission-boundaries/verify.md'

  - コントリビュート: 'contribute.md'
  - License: 'license.md'
